"""add password reset fields

Revision ID: 436cdefb599b
Revises: 4630ce283af4
Create Date: 2026-08-02 21:12:18.427520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '436cdefb599b'
down_revision: Union[str, Sequence[str], None] = '4630ce283af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # History fix: autogenerate emitted a drop of `email_deliveries` here (the model was not registered
    # at the time); applying it destroys delivery history. Same fix as 4630ce283af4. The table is required by later revisions and exists in deployed
    # databases, so it is intentionally NOT dropped.
    op.add_column('users', sa.Column('reset_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_token_expire', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_token_expire')
    op.drop_column('users', 'reset_token')
    # ### end Alembic commands ###
