"""add from_name to campaigns

Revision ID: 4630ce283af4
Revises: 267cbb5b6c03
Create Date: 2026-07-25 20:24:19.090563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4630ce283af4'
down_revision: Union[str, Sequence[str], None] = '267cbb5b6c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # History fix: autogenerate emitted a drop of `email_deliveries` here (the model was not registered
    # at the time); applying it destroys delivery history. The table is required by later revisions
    # (e.g. b2c3d4e5f6a7) and exists in deployed databases, so it is intentionally NOT dropped.
    op.add_column('campaigns', sa.Column('from_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'from_name')
    # ### end Alembic commands ###
