"""add from_name to campaigns

Revision ID: 4630ce283af4
Revises: 267cbb5b6c03
Create Date: 2026-07-25 20:24:19.090563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4630ce283af4'
down_revision: Union[str, Sequence[str], None] = '267cbb5b6c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_deliveries_campaign_id'), table_name='email_deliveries')
    op.drop_index(op.f('ix_email_deliveries_contact_id'), table_name='email_deliveries')
    op.drop_index(op.f('ix_email_deliveries_id'), table_name='email_deliveries')
    op.drop_table('email_deliveries')
    op.add_column('campaigns', sa.Column('from_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'from_name')
    op.create_table('email_deliveries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('campaign_id', sa.INTEGER(), nullable=False),
    sa.Column('contact_id', sa.INTEGER(), nullable=False),
    sa.Column('sender_account_id', sa.INTEGER(), nullable=True),
    sa.Column('recipient_email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('status', sa.VARCHAR(length=7), nullable=False),
    sa.Column('error_message', sa.VARCHAR(length=500), nullable=True),
    sa.Column('sent_at', sa.DATETIME(), nullable=True),
    sa.Column('opened_at', sa.DATETIME(), nullable=True),
    sa.Column('clicked_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_account_id'], ['sender_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_deliveries_id'), 'email_deliveries', ['id'], unique=False)
    op.create_index(op.f('ix_email_deliveries_contact_id'), 'email_deliveries', ['contact_id'], unique=False)
    op.create_index(op.f('ix_email_deliveries_campaign_id'), 'email_deliveries', ['campaign_id'], unique=False)
    # ### end Alembic commands ###
